name: Run Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
env:
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12.3'

      - name: Run Script
        run: |
          pip install python-dotenv
          pip install psycopg
          pip install aiohttp
          python main.py
